// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Auth is the predicate function for auth builders.
type Auth func(*sql.Selector)

// JobHistory is the predicate function for jobhistory builders.
type JobHistory func(*sql.Selector)

// OrgUnit is the predicate function for orgunit builders.
type OrgUnit func(*sql.Selector)

// OrgUnitMember is the predicate function for orgunitmember builders.
type OrgUnitMember func(*sql.Selector)

// OrgUnitPosition is the predicate function for orgunitposition builders.
type OrgUnitPosition func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// Resource is the predicate function for resource builders.
type Resource func(*sql.Selector)

// System is the predicate function for system builders.
type System func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
