// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"fmt"
	"sync"
	"sync/atomic"
	"wing/models/ent/auth"
	"wing/models/ent/jobhistory"
	"wing/models/ent/organization"
	"wing/models/ent/orgunit"
	"wing/models/ent/orgunitmember"
	"wing/models/ent/orgunitposition"
	"wing/models/ent/resource"
	"wing/models/ent/system"
	"wing/models/ent/user"

	"entgo.io/contrib/entgql"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/schema"
	"github.com/99designs/gqlgen/graphql"
	"github.com/hashicorp/go-multierror"
	"golang.org/x/sync/semaphore"
)

// Noder wraps the basic Node method.
type Noder interface {
	Node(context.Context) (*Node, error)
}

// Node in the graph.
type Node struct {
	ID     int      `json:"id,omitempty"`     // node id.
	Type   string   `json:"type,omitempty"`   // node type.
	Fields []*Field `json:"fields,omitempty"` // node fields.
	Edges  []*Edge  `json:"edges,omitempty"`  // node edges.
}

// Field of a node.
type Field struct {
	Type  string `json:"type,omitempty"`  // field type.
	Name  string `json:"name,omitempty"`  // field name (as in struct).
	Value string `json:"value,omitempty"` // stringified value.
}

// Edges between two nodes.
type Edge struct {
	Type string `json:"type,omitempty"` // edge type.
	Name string `json:"name,omitempty"` // edge name.
	IDs  []int  `json:"ids,omitempty"`  // node ids (where this edge point to).
}

func (a *Auth) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     a.ID,
		Type:   "Auth",
		Fields: make([]*Field, 2),
		Edges:  make([]*Edge, 1),
	}
	var buf []byte
	if buf, err = json.Marshal(a.LastAuthTime); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "last_auth_time",
		Value: string(buf),
	}
	if buf, err = json.Marshal(a.AuthType); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "auth.AuthType",
		Name:  "auth_type",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "User",
		Name: "belong_to",
	}
	err = a.QueryBelongTo().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

func (jh *JobHistory) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     jh.ID,
		Type:   "JobHistory",
		Fields: make([]*Field, 4),
		Edges:  make([]*Edge, 2),
	}
	var buf []byte
	if buf, err = json.Marshal(jh.CreateByUser); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "int",
		Name:  "create_by_user",
		Value: string(buf),
	}
	if buf, err = json.Marshal(jh.CreateTime); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "create_time",
		Value: string(buf),
	}
	if buf, err = json.Marshal(jh.Date); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "time.Time",
		Name:  "date",
		Value: string(buf),
	}
	if buf, err = json.Marshal(jh.JobEntryLeaveType); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "jobhistory.JobEntryLeaveType",
		Name:  "job_entry_leave_type",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "User",
		Name: "create_by",
	}
	err = jh.QueryCreateBy().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "User",
		Name: "belong_to",
	}
	err = jh.QueryBelongTo().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

func (ou *OrgUnit) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     ou.ID,
		Type:   "OrgUnit",
		Fields: make([]*Field, 6),
		Edges:  make([]*Edge, 7),
	}
	var buf []byte
	if buf, err = json.Marshal(ou.CreateByUser); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "int",
		Name:  "create_by_user",
		Value: string(buf),
	}
	if buf, err = json.Marshal(ou.UpdateByUser); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "int",
		Name:  "update_by_user",
		Value: string(buf),
	}
	if buf, err = json.Marshal(ou.CreateTime); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "time.Time",
		Name:  "create_time",
		Value: string(buf),
	}
	if buf, err = json.Marshal(ou.UpdateTime); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "time.Time",
		Name:  "update_time",
		Value: string(buf),
	}
	if buf, err = json.Marshal(ou.Name); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(ou.Duty); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "string",
		Name:  "duty",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "User",
		Name: "create_by",
	}
	err = ou.QueryCreateBy().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "User",
		Name: "update_by",
	}
	err = ou.QueryUpdateBy().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[2] = &Edge{
		Type: "OrgUnitMember",
		Name: "members",
	}
	err = ou.QueryMembers().
		Select(orgunitmember.FieldID).
		Scan(ctx, &node.Edges[2].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[3] = &Edge{
		Type: "OrgUnitPosition",
		Name: "positions",
	}
	err = ou.QueryPositions().
		Select(orgunitposition.FieldID).
		Scan(ctx, &node.Edges[3].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[4] = &Edge{
		Type: "OrgUnit",
		Name: "supUnit",
	}
	err = ou.QuerySupUnit().
		Select(orgunit.FieldID).
		Scan(ctx, &node.Edges[4].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[5] = &Edge{
		Type: "OrgUnit",
		Name: "subUnits",
	}
	err = ou.QuerySubUnits().
		Select(orgunit.FieldID).
		Scan(ctx, &node.Edges[5].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[6] = &Edge{
		Type: "Organization",
		Name: "belongToOrg",
	}
	err = ou.QueryBelongToOrg().
		Select(organization.FieldID).
		Scan(ctx, &node.Edges[6].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

func (oum *OrgUnitMember) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     oum.ID,
		Type:   "OrgUnitMember",
		Fields: make([]*Field, 8),
		Edges:  make([]*Edge, 5),
	}
	var buf []byte
	if buf, err = json.Marshal(oum.CreateByUser); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "int",
		Name:  "create_by_user",
		Value: string(buf),
	}
	if buf, err = json.Marshal(oum.UpdateByUser); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "int",
		Name:  "update_by_user",
		Value: string(buf),
	}
	if buf, err = json.Marshal(oum.CreateTime); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "time.Time",
		Name:  "create_time",
		Value: string(buf),
	}
	if buf, err = json.Marshal(oum.UpdateTime); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "time.Time",
		Name:  "update_time",
		Value: string(buf),
	}
	if buf, err = json.Marshal(oum.IsAdditional); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "bool",
		Name:  "is_additional",
		Value: string(buf),
	}
	if buf, err = json.Marshal(oum.UserID); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "int",
		Name:  "user_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(oum.OrgUnitID); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "int",
		Name:  "org_unit_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(oum.OrgUnitPositionID); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "int",
		Name:  "org_unit_position_id",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "User",
		Name: "create_by",
	}
	err = oum.QueryCreateBy().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "User",
		Name: "update_by",
	}
	err = oum.QueryUpdateBy().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[2] = &Edge{
		Type: "User",
		Name: "user",
	}
	err = oum.QueryUser().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[2].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[3] = &Edge{
		Type: "OrgUnitPosition",
		Name: "position",
	}
	err = oum.QueryPosition().
		Select(orgunitposition.FieldID).
		Scan(ctx, &node.Edges[3].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[4] = &Edge{
		Type: "OrgUnit",
		Name: "belongToOrgUnit",
	}
	err = oum.QueryBelongToOrgUnit().
		Select(orgunit.FieldID).
		Scan(ctx, &node.Edges[4].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

func (oup *OrgUnitPosition) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     oup.ID,
		Type:   "OrgUnitPosition",
		Fields: make([]*Field, 8),
		Edges:  make([]*Edge, 4),
	}
	var buf []byte
	if buf, err = json.Marshal(oup.CreateByUser); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "int",
		Name:  "create_by_user",
		Value: string(buf),
	}
	if buf, err = json.Marshal(oup.UpdateByUser); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "int",
		Name:  "update_by_user",
		Value: string(buf),
	}
	if buf, err = json.Marshal(oup.CreateTime); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "time.Time",
		Name:  "create_time",
		Value: string(buf),
	}
	if buf, err = json.Marshal(oup.UpdateTime); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "time.Time",
		Name:  "update_time",
		Value: string(buf),
	}
	if buf, err = json.Marshal(oup.Name); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(oup.Duty); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "string",
		Name:  "duty",
		Value: string(buf),
	}
	if buf, err = json.Marshal(oup.Level); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "int",
		Name:  "level",
		Value: string(buf),
	}
	if buf, err = json.Marshal(oup.OrgUnitID); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "int",
		Name:  "org_unit_id",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "User",
		Name: "create_by",
	}
	err = oup.QueryCreateBy().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "User",
		Name: "update_by",
	}
	err = oup.QueryUpdateBy().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[2] = &Edge{
		Type: "OrgUnitMember",
		Name: "belongToOrgUnitMembers",
	}
	err = oup.QueryBelongToOrgUnitMembers().
		Select(orgunitmember.FieldID).
		Scan(ctx, &node.Edges[2].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[3] = &Edge{
		Type: "OrgUnit",
		Name: "belongToOrgUnit",
	}
	err = oup.QueryBelongToOrgUnit().
		Select(orgunit.FieldID).
		Scan(ctx, &node.Edges[3].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

func (o *Organization) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     o.ID,
		Type:   "Organization",
		Fields: make([]*Field, 5),
		Edges:  make([]*Edge, 4),
	}
	var buf []byte
	if buf, err = json.Marshal(o.CreateByUser); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "int",
		Name:  "create_by_user",
		Value: string(buf),
	}
	if buf, err = json.Marshal(o.UpdateByUser); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "int",
		Name:  "update_by_user",
		Value: string(buf),
	}
	if buf, err = json.Marshal(o.CreateTime); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "time.Time",
		Name:  "create_time",
		Value: string(buf),
	}
	if buf, err = json.Marshal(o.UpdateTime); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "time.Time",
		Name:  "update_time",
		Value: string(buf),
	}
	if buf, err = json.Marshal(o.Name); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "name",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "User",
		Name: "create_by",
	}
	err = o.QueryCreateBy().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "User",
		Name: "update_by",
	}
	err = o.QueryUpdateBy().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[2] = &Edge{
		Type: "OrgUnit",
		Name: "units",
	}
	err = o.QueryUnits().
		Select(orgunit.FieldID).
		Scan(ctx, &node.Edges[2].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[3] = &Edge{
		Type: "User",
		Name: "staffs",
	}
	err = o.QueryStaffs().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[3].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

func (r *Resource) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     r.ID,
		Type:   "Resource",
		Fields: make([]*Field, 2),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(r.Name); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "string",
		Name:  "name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(r.Type); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "string",
		Name:  "type",
		Value: string(buf),
	}
	return node, nil
}

func (s *System) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     s.ID,
		Type:   "System",
		Fields: make([]*Field, 5),
		Edges:  make([]*Edge, 2),
	}
	var buf []byte
	if buf, err = json.Marshal(s.CreateByUser); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "int",
		Name:  "create_by_user",
		Value: string(buf),
	}
	if buf, err = json.Marshal(s.UpdateByUser); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "int",
		Name:  "update_by_user",
		Value: string(buf),
	}
	if buf, err = json.Marshal(s.CreateTime); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "time.Time",
		Name:  "create_time",
		Value: string(buf),
	}
	if buf, err = json.Marshal(s.UpdateTime); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "time.Time",
		Name:  "update_time",
		Value: string(buf),
	}
	if buf, err = json.Marshal(s.Name); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "name",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "User",
		Name: "create_by",
	}
	err = s.QueryCreateBy().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "User",
		Name: "update_by",
	}
	err = s.QueryUpdateBy().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

func (u *User) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     u.ID,
		Type:   "User",
		Fields: make([]*Field, 19),
		Edges:  make([]*Edge, 8),
	}
	var buf []byte
	if buf, err = json.Marshal(u.CreateByUser); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "int",
		Name:  "create_by_user",
		Value: string(buf),
	}
	if buf, err = json.Marshal(u.UpdateByUser); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "int",
		Name:  "update_by_user",
		Value: string(buf),
	}
	if buf, err = json.Marshal(u.CreateTime); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "time.Time",
		Name:  "create_time",
		Value: string(buf),
	}
	if buf, err = json.Marshal(u.UpdateTime); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "time.Time",
		Name:  "update_time",
		Value: string(buf),
	}
	if buf, err = json.Marshal(u.AccountName); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "account_name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(u.StaffType); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "user.StaffType",
		Name:  "staff_type",
		Value: string(buf),
	}
	if buf, err = json.Marshal(u.IsOnJob); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "bool",
		Name:  "is_on_job",
		Value: string(buf),
	}
	if buf, err = json.Marshal(u.FamilyName); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "string",
		Name:  "family_name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(u.GivenName); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "string",
		Name:  "given_name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(u.DisplayName); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "string",
		Name:  "display_name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(u.Birthday); err != nil {
		return nil, err
	}
	node.Fields[10] = &Field{
		Type:  "time.Time",
		Name:  "birthday",
		Value: string(buf),
	}
	if buf, err = json.Marshal(u.IDNumber); err != nil {
		return nil, err
	}
	node.Fields[11] = &Field{
		Type:  "string",
		Name:  "id_number",
		Value: string(buf),
	}
	if buf, err = json.Marshal(u.Sex); err != nil {
		return nil, err
	}
	node.Fields[12] = &Field{
		Type:  "user.Sex",
		Name:  "sex",
		Value: string(buf),
	}
	if buf, err = json.Marshal(u.PhoneNumber); err != nil {
		return nil, err
	}
	node.Fields[13] = &Field{
		Type:  "string",
		Name:  "phone_number",
		Value: string(buf),
	}
	if buf, err = json.Marshal(u.Address); err != nil {
		return nil, err
	}
	node.Fields[14] = &Field{
		Type:  "string",
		Name:  "address",
		Value: string(buf),
	}
	if buf, err = json.Marshal(u.StaffID); err != nil {
		return nil, err
	}
	node.Fields[15] = &Field{
		Type:  "string",
		Name:  "staff_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(u.PersonalEmail); err != nil {
		return nil, err
	}
	node.Fields[16] = &Field{
		Type:  "string",
		Name:  "personal_email",
		Value: string(buf),
	}
	if buf, err = json.Marshal(u.IntranetWorkEmail); err != nil {
		return nil, err
	}
	node.Fields[17] = &Field{
		Type:  "string",
		Name:  "intranet_work_email",
		Value: string(buf),
	}
	if buf, err = json.Marshal(u.ExtranetWorkEmail); err != nil {
		return nil, err
	}
	node.Fields[18] = &Field{
		Type:  "string",
		Name:  "extranet_work_email",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "User",
		Name: "create_by",
	}
	err = u.QueryCreateBy().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "User",
		Name: "update_by",
	}
	err = u.QueryUpdateBy().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[2] = &Edge{
		Type: "Auth",
		Name: "authHistories",
	}
	err = u.QueryAuthHistories().
		Select(auth.FieldID).
		Scan(ctx, &node.Edges[2].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[3] = &Edge{
		Type: "JobHistory",
		Name: "jobHistories",
	}
	err = u.QueryJobHistories().
		Select(jobhistory.FieldID).
		Scan(ctx, &node.Edges[3].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[4] = &Edge{
		Type: "User",
		Name: "creates",
	}
	err = u.QueryCreates().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[4].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[5] = &Edge{
		Type: "User",
		Name: "updates",
	}
	err = u.QueryUpdates().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[5].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[6] = &Edge{
		Type: "OrgUnitMember",
		Name: "belongToOrgUnitMembers",
	}
	err = u.QueryBelongToOrgUnitMembers().
		Select(orgunitmember.FieldID).
		Scan(ctx, &node.Edges[6].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[7] = &Edge{
		Type: "Organization",
		Name: "belongToOg",
	}
	err = u.QueryBelongToOg().
		Select(organization.FieldID).
		Scan(ctx, &node.Edges[7].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

func (c *Client) Node(ctx context.Context, id int) (*Node, error) {
	n, err := c.Noder(ctx, id)
	if err != nil {
		return nil, err
	}
	return n.Node(ctx)
}

var errNodeInvalidID = &NotFoundError{"node"}

// NodeOption allows configuring the Noder execution using functional options.
type NodeOption func(*nodeOptions)

// WithNodeType sets the node Type resolver function (i.e. the table to query).
// If was not provided, the table will be derived from the universal-id
// configuration as described in: https://entgo.io/docs/migrate/#universal-ids.
func WithNodeType(f func(context.Context, int) (string, error)) NodeOption {
	return func(o *nodeOptions) {
		o.nodeType = f
	}
}

// WithFixedNodeType sets the Type of the node to a fixed value.
func WithFixedNodeType(t string) NodeOption {
	return WithNodeType(func(context.Context, int) (string, error) {
		return t, nil
	})
}

type nodeOptions struct {
	nodeType func(context.Context, int) (string, error)
}

func (c *Client) newNodeOpts(opts []NodeOption) *nodeOptions {
	nopts := &nodeOptions{}
	for _, opt := range opts {
		opt(nopts)
	}
	if nopts.nodeType == nil {
		nopts.nodeType = func(ctx context.Context, id int) (string, error) {
			return c.tables.nodeType(ctx, c.driver, id)
		}
	}
	return nopts
}

// Noder returns a Node by its id. If the NodeType was not provided, it will
// be derived from the id value according to the universal-id configuration.
//
//		c.Noder(ctx, id)
//		c.Noder(ctx, id, ent.WithNodeType(pet.Table))
//
func (c *Client) Noder(ctx context.Context, id int, opts ...NodeOption) (_ Noder, err error) {
	defer func() {
		if IsNotFound(err) {
			err = multierror.Append(err, entgql.ErrNodeNotFound(id))
		}
	}()
	table, err := c.newNodeOpts(opts).nodeType(ctx, id)
	if err != nil {
		return nil, err
	}
	return c.noder(ctx, table, id)
}

func (c *Client) noder(ctx context.Context, table string, id int) (Noder, error) {
	switch table {
	case auth.Table:
		n, err := c.Auth.Query().
			Where(auth.ID(id)).
			CollectFields(ctx, "Auth").
			Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case jobhistory.Table:
		n, err := c.JobHistory.Query().
			Where(jobhistory.ID(id)).
			CollectFields(ctx, "JobHistory").
			Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case orgunit.Table:
		n, err := c.OrgUnit.Query().
			Where(orgunit.ID(id)).
			CollectFields(ctx, "OrgUnit").
			Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case orgunitmember.Table:
		n, err := c.OrgUnitMember.Query().
			Where(orgunitmember.ID(id)).
			CollectFields(ctx, "OrgUnitMember").
			Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case orgunitposition.Table:
		n, err := c.OrgUnitPosition.Query().
			Where(orgunitposition.ID(id)).
			CollectFields(ctx, "OrgUnitPosition").
			Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case organization.Table:
		n, err := c.Organization.Query().
			Where(organization.ID(id)).
			CollectFields(ctx, "Organization").
			Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case resource.Table:
		n, err := c.Resource.Query().
			Where(resource.ID(id)).
			CollectFields(ctx, "Resource").
			Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case system.Table:
		n, err := c.System.Query().
			Where(system.ID(id)).
			CollectFields(ctx, "System").
			Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case user.Table:
		n, err := c.User.Query().
			Where(user.ID(id)).
			CollectFields(ctx, "User").
			Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	default:
		return nil, fmt.Errorf("cannot resolve noder from table %q: %w", table, errNodeInvalidID)
	}
}

func (c *Client) Noders(ctx context.Context, ids []int, opts ...NodeOption) ([]Noder, error) {
	switch len(ids) {
	case 1:
		noder, err := c.Noder(ctx, ids[0], opts...)
		if err != nil {
			return nil, err
		}
		return []Noder{noder}, nil
	case 0:
		return []Noder{}, nil
	}

	noders := make([]Noder, len(ids))
	errors := make([]error, len(ids))
	tables := make(map[string][]int)
	id2idx := make(map[int][]int, len(ids))
	nopts := c.newNodeOpts(opts)
	for i, id := range ids {
		table, err := nopts.nodeType(ctx, id)
		if err != nil {
			errors[i] = err
			continue
		}
		tables[table] = append(tables[table], id)
		id2idx[id] = append(id2idx[id], i)
	}

	for table, ids := range tables {
		nodes, err := c.noders(ctx, table, ids)
		if err != nil {
			for _, id := range ids {
				for _, idx := range id2idx[id] {
					errors[idx] = err
				}
			}
		} else {
			for i, id := range ids {
				for _, idx := range id2idx[id] {
					noders[idx] = nodes[i]
				}
			}
		}
	}

	for i, id := range ids {
		if errors[i] == nil {
			if noders[i] != nil {
				continue
			}
			errors[i] = entgql.ErrNodeNotFound(id)
		} else if IsNotFound(errors[i]) {
			errors[i] = multierror.Append(errors[i], entgql.ErrNodeNotFound(id))
		}
		ctx := graphql.WithPathContext(ctx,
			graphql.NewPathWithIndex(i),
		)
		graphql.AddError(ctx, errors[i])
	}
	return noders, nil
}

func (c *Client) noders(ctx context.Context, table string, ids []int) ([]Noder, error) {
	noders := make([]Noder, len(ids))
	idmap := make(map[int][]*Noder, len(ids))
	for i, id := range ids {
		idmap[id] = append(idmap[id], &noders[i])
	}
	switch table {
	case auth.Table:
		nodes, err := c.Auth.Query().
			Where(auth.IDIn(ids...)).
			CollectFields(ctx, "Auth").
			All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case jobhistory.Table:
		nodes, err := c.JobHistory.Query().
			Where(jobhistory.IDIn(ids...)).
			CollectFields(ctx, "JobHistory").
			All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case orgunit.Table:
		nodes, err := c.OrgUnit.Query().
			Where(orgunit.IDIn(ids...)).
			CollectFields(ctx, "OrgUnit").
			All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case orgunitmember.Table:
		nodes, err := c.OrgUnitMember.Query().
			Where(orgunitmember.IDIn(ids...)).
			CollectFields(ctx, "OrgUnitMember").
			All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case orgunitposition.Table:
		nodes, err := c.OrgUnitPosition.Query().
			Where(orgunitposition.IDIn(ids...)).
			CollectFields(ctx, "OrgUnitPosition").
			All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case organization.Table:
		nodes, err := c.Organization.Query().
			Where(organization.IDIn(ids...)).
			CollectFields(ctx, "Organization").
			All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case resource.Table:
		nodes, err := c.Resource.Query().
			Where(resource.IDIn(ids...)).
			CollectFields(ctx, "Resource").
			All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case system.Table:
		nodes, err := c.System.Query().
			Where(system.IDIn(ids...)).
			CollectFields(ctx, "System").
			All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case user.Table:
		nodes, err := c.User.Query().
			Where(user.IDIn(ids...)).
			CollectFields(ctx, "User").
			All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	default:
		return nil, fmt.Errorf("cannot resolve noders from table %q: %w", table, errNodeInvalidID)
	}
	return noders, nil
}

type tables struct {
	once  sync.Once
	sem   *semaphore.Weighted
	value atomic.Value
}

func (t *tables) nodeType(ctx context.Context, drv dialect.Driver, id int) (string, error) {
	tables, err := t.Load(ctx, drv)
	if err != nil {
		return "", err
	}
	idx := int(id / (1<<32 - 1))
	if idx < 0 || idx >= len(tables) {
		return "", fmt.Errorf("cannot resolve table from id %v: %w", id, errNodeInvalidID)
	}
	return tables[idx], nil
}

func (t *tables) Load(ctx context.Context, drv dialect.Driver) ([]string, error) {
	if tables := t.value.Load(); tables != nil {
		return tables.([]string), nil
	}
	t.once.Do(func() { t.sem = semaphore.NewWeighted(1) })
	if err := t.sem.Acquire(ctx, 1); err != nil {
		return nil, err
	}
	defer t.sem.Release(1)
	if tables := t.value.Load(); tables != nil {
		return tables.([]string), nil
	}
	tables, err := t.load(ctx, drv)
	if err == nil {
		t.value.Store(tables)
	}
	return tables, err
}

func (*tables) load(ctx context.Context, drv dialect.Driver) ([]string, error) {
	rows := &sql.Rows{}
	query, args := sql.Dialect(drv.Dialect()).
		Select("type").
		From(sql.Table(schema.TypeTable)).
		OrderBy(sql.Asc("id")).
		Query()
	if err := drv.Query(ctx, query, args, rows); err != nil {
		return nil, err
	}
	defer rows.Close()
	var tables []string
	return tables, sql.ScanSlice(rows, &tables)
}
